// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: misc.sql

package database

import (
	"context"
)

const flushTables = `-- name: FlushTables :exec
DELETE FROM users
`

func (q *Queries) FlushTables(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, flushTables)
	return err
}
